"""Manually publish text from the crew-supplied, unchanged PDF; never unlock PDFs."""
import hashlib
import json
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / "references" / "race-rules-wtr-atlantic-2025-v1.0.pdf"
reader = PdfReader(PDF)
if reader.is_encrypted:
    raise SystemExit("Protected PDF: stop and request an authorised unprotected source.")

topics = [
    "Boat designs and crew size",
    "Mandatory equipment, propulsion and safety at sea",
    "Refuse, tracking and communications",
    "Emergency communications, medical kit and cabin hatches",
    "Cooking, oars, awnings and navigation",
    "Steering, qualification and training",
    "Emergency water, ballast and self-righting",
    "Resupplies, assistance and finishing",
    "Finish procedures, branding and penalties",
    "Penalties and life-saving equipment",
    "Media approval and safety-at-sea penalties",
]
if len(reader.pages) != len(topics):
    raise SystemExit("Page count changed: review edition and page descriptions before publishing.")
pages = []
for number, page in enumerate(reader.pages, 1):
    text = page.extract_text()
    if not text or not text.strip():
        raise SystemExit(f"No extractable text on PDF page {number}; manual review required.")
    pages.append({"page": number, "topic": topics[number - 1], "text": text.strip()})

data = {
    "title": "Race Rules WTR - Atlantic 2025 V1.0",
    "edition": "Atlantic 2025 v1.0",
    "file": "references/race-rules-wtr-atlantic-2025-v1.0.pdf",
    "source": "https://microsofteur.sharepoint.com/teams/growoceancrew/Shared%20Documents/App%20Content/Rules%20and%20Safety/Race%20Rules%20WTR%20-%20Atlantic%202025%20V1.0.pdf",
    "sha256": hashlib.sha256(PDF.read_bytes()).hexdigest(),
    "downloaded": "2026-09-09",
    "copyright": "© Atlantic Campaigns. All rights reserved. Crew-provided reference.",
    "pages": pages,
}
(ROOT / "js" / "data" / "rules-data.js").write_text(
    "// Generated by tools/extract-rules.py from the unchanged crew-provided PDF.\n"
    "export const RULES_DOCUMENT = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8",
)
print(f"Published {len(pages)} searchable PDF pages. SHA-256: {data['sha256']}")
